# Generated by Django 5.0.6 on 2026-07-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='encryption_key',
            field=models.CharField(blank=True, help_text='From scripts/process_video.py output (key.txt) — paste key here. Only ever served to a client after video-token verification.', max_length=64),
        ),
        migrations.AddField(
            model_name='lesson',
            name='encryption_key_id',
            field=models.CharField(blank=True, help_text='From scripts/process_video.py output (key.txt) — paste key_id here', max_length=64),
        ),
    ]
